#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in *; do
	# check if file contains a dash
	if [[ $file == *-* ]]; then
		 # extract the name after the dash
		 name="${file#*-}"

		 echo "$name"
	else
		echo "$file"
	fi
done
