#!/usr/bin/env bash
#display all active ipv4

# Get active IPv4 IPs
ipv4_addresses=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | tr '\n' ' ')

# Display the result
for ip in $ipv4_addresses; do
	echo "$ip"
done
